---
language: "python"
python: "2.7"

env:
  - SITE="test.yml"

before_install:
  - "sudo apt-get update -qq"

install:
  - "pip install ansible==1.6.2"
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"

script:
  - "ansible-playbook tests/$SITE -i tests/inventory --syntax-check"
  - "ansible-playbook tests/$SITE -i tests/inventory --connection=local -vvvv"
  - >
    ansible-playbook tests/$SITE -i tests/inventory --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  - "ping -c 1 foo.dev"